apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 5000
      timeout: 30
    editable: false

  - name: Langfuse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://langfuse-clickhouse:8123
    jsonData:
      server: langfuse-clickhouse
      port: 9000
      username: clickhouse
      defaultDatabase: default
    secureJsonData:
      password: ${LANGFUSE_CLICKHOUSE_PASSWORD}
    editable: false
