#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Apex - Investor Intelligence Reports

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECKS
# ============================================

# Check if we're in the correct directory
if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found. Please run this script from the project root.${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}node_modules not found. Running npm install...${NC}"
    npm install
fi

# ============================================
# CRITICAL DEPENDENCY CHECK
# ============================================

echo ""
echo "Checking critical dependencies..."

# Check if recharts-to-png is installed (CRITICAL for this feature)
if npm list recharts-to-png &>/dev/null; then
    echo -e "${GREEN}✓ recharts-to-png is installed${NC}"
else
    echo -e "${YELLOW}⚠️  WARNING: recharts-to-png not installed${NC}"
    echo "This library is CRITICAL for chart-to-PDF conversion in investor reports."
    echo "Installing recharts-to-png..."
    npm install recharts-to-png
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ recharts-to-png installed successfully${NC}"
    else
        echo -e "${RED}✗ Failed to install recharts-to-png${NC}"
        echo "Please manually run: npm install recharts-to-png"
        exit 1
    fi
fi

# Check if @react-pdf/renderer is installed
if npm list @react-pdf/renderer &>/dev/null; then
    echo -e "${GREEN}✓ @react-pdf/renderer is installed${NC}"
else
    echo -e "${RED}✗ @react-pdf/renderer not found${NC}"
    echo "Installing @react-pdf/renderer..."
    npm install @react-pdf/renderer
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

# Start Next.js in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js App: http://localhost:3000"
echo "  Database:    PostgreSQL (Neon - remote hosted)"
echo ""
echo "Investor Reports Feature:"
echo "  Dashboard:   http://localhost:3000/dashboard/reports/investor"
echo "  API Route:   http://localhost:3000/api/reports/investor (POST)"
echo ""
echo "Critical Libraries Verified:"
echo "  ✓ @react-pdf/renderer  (PDF generation)"
echo "  ✓ recharts-to-png      (Chart embedding in PDFs)"
echo ""
echo "To stop all services, press Ctrl+C"
echo ""

# Keep script running
wait $NEXTJS_PID
