/**
 * llms.txt generator — crawls a site, extracts page titles + descriptions,
 * and builds a file following the llmstxt.org structure so AI crawlers
 * can discover the canonical pages without scraping full HTML.
 *
 * Input:  discovered URLs (same pipeline as site-patch)
 * Output: a single markdown-flavoured llms.txt string
 *
 * Grouping heuristic: bucket pages by URL path prefix so /docs/* goes under
 * "Docs", /blog/* under "Blog", /features/* under "Features", etc. Pages
 * that don't match a known prefix fall into "Pages".
 */

import * as cheerio from "cheerio";

export interface PageMeta {
  url: string;
  title: string;
  description: string;
}

const FETCH_TIMEOUT_MS = 15000;

async function fetchPageMeta(url: string): Promise<PageMeta | null> {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
    const res = await fetch(url, {
      signal: ctrl.signal,
      redirect: "follow",
      headers: {
        "User-Agent":
          "Mozilla/5.0 (compatible; ApexGEO-LlmsTxtBuilder/1.0; +https://apexgeo.app)",
      },
    });
    clearTimeout(t);
    if (!res.ok) return null;
    const ctype = res.headers.get("content-type") ?? "";
    if (!ctype.toLowerCase().includes("text/html")) return null;
    const html = await res.text();

    const $ = cheerio.load(html);
    const title =
      $("title").first().text().trim() ||
      $('meta[property="og:title"]').attr("content")?.trim() ||
      $("h1").first().text().trim() ||
      url;
    const description =
      $('meta[name="description"]').attr("content")?.trim() ||
      $('meta[property="og:description"]').attr("content")?.trim() ||
      "";

    return { url, title: collapseWs(title), description: collapseWs(description) };
  } catch {
    return null;
  }
}

function collapseWs(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

/**
 * Group pages by URL pathname prefix. A page is only promoted to its own
 * section when the first path segment is a real directory (the path has
 * more than one segment, OR the first segment matches a known section
 * label like "docs"/"blog"/"features"). Everything else falls into
 * "Pages" so flat sites don't get shredded into one-file sections like
 * "About.Html", "Services.Html", etc.
 */
function groupByPrefix(pages: PageMeta[], rootUrl: URL): Map<string, PageMeta[]> {
  const buckets = new Map<string, PageMeta[]>();

  for (const p of pages) {
    let bucket = "Pages";
    try {
      const u = new URL(p.url);
      const segs = u.pathname.split("/").filter(Boolean);
      if (segs.length === 0) {
        bucket = "Home";
      } else if (u.host === rootUrl.host) {
        // Strip extensions before matching so "/docs" and "/docs.html" both
        // land in the docs bucket.
        const firstRaw = segs[0].toLowerCase();
        const first = firstRaw.replace(/\.[a-z0-9]+$/i, "");
        const known = SECTION_LABELS[first];
        if (known) {
          bucket = known;
        } else if (segs.length >= 2) {
          // Only promote unknown prefixes to a section when the URL has a
          // real directory underneath (e.g. /features/pricing).
          bucket = capitalize(first);
        }
      }
    } catch {
      /* fall through to "Pages" */
    }
    const list = buckets.get(bucket) ?? [];
    list.push(p);
    buckets.set(bucket, list);
  }

  return buckets;
}

const SECTION_LABELS: Record<string, string> = {
  docs: "Docs",
  documentation: "Docs",
  guides: "Guides",
  blog: "Blog",
  news: "News",
  features: "Features",
  product: "Product",
  products: "Products",
  pricing: "Pricing",
  about: "About",
  company: "Company",
  customers: "Customers",
  "case-studies": "Case studies",
  api: "API",
  help: "Help",
  support: "Support",
  legal: "Legal",
};

function capitalize(s: string): string {
  if (!s) return s;
  return s
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Render the final llms.txt string following the llmstxt.org structure:
 *
 *   # Site title
 *   > Brief description
 *   {optional paragraph}
 *
 *   ## Section
 *   - [Page title](url): description
 */
export function renderLlmsTxt(opts: {
  siteTitle: string;
  siteDescription: string;
  pages: PageMeta[];
  rootUrl: URL;
}): string {
  const { siteTitle, siteDescription, pages, rootUrl } = opts;

  const lines: string[] = [];
  lines.push(`# ${siteTitle || rootUrl.hostname}`);
  lines.push("");
  if (siteDescription) {
    lines.push(`> ${siteDescription}`);
    lines.push("");
  }
  lines.push(
    `Generated by Apex (${new Date().toISOString().slice(0, 10)}) — canonical pages for AI crawlers.`,
  );
  lines.push("");

  const buckets = groupByPrefix(pages, rootUrl);
  // Home first, then Docs/Guides, then alphabetical, then "Pages" last.
  const orderedKeys = [...buckets.keys()].sort((a, b) => {
    const rank = (k: string) => {
      if (k === "Home") return 0;
      if (k === "Docs") return 1;
      if (k === "Guides") return 2;
      if (k === "Pages") return 1000;
      return 100;
    };
    const ra = rank(a);
    const rb = rank(b);
    if (ra !== rb) return ra - rb;
    return a.localeCompare(b);
  });

  for (const key of orderedKeys) {
    const list = buckets.get(key)!;
    lines.push(`## ${key}`);
    for (const p of list) {
      const title = p.title || p.url;
      const desc = p.description ? `: ${p.description}` : "";
      lines.push(`- [${title}](${p.url})${desc}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Fetch metadata for many URLs with light concurrency. Returns only pages
 * that returned HTML with a usable title.
 */
export async function collectPageMeta(
  urls: string[],
  opts: { concurrency?: number; onProgress?: (done: number, total: number) => void } = {},
): Promise<PageMeta[]> {
  const concurrency = opts.concurrency ?? 4;
  const out: PageMeta[] = [];
  let done = 0;

  const queue = [...urls];
  const workers: Promise<void>[] = [];

  const work = async () => {
    while (queue.length > 0) {
      const url = queue.shift();
      if (!url) return;
      const meta = await fetchPageMeta(url);
      if (meta) out.push(meta);
      done += 1;
      opts.onProgress?.(done, urls.length);
    }
  };

  for (let i = 0; i < concurrency; i++) workers.push(work());
  await Promise.all(workers);

  // Preserve input order so llms.txt is deterministic.
  const index = new Map(urls.map((u, i) => [u, i]));
  out.sort((a, b) => (index.get(a.url) ?? 0) - (index.get(b.url) ?? 0));

  return out;
}
