#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003

set -e

echo "========================================"
echo "AI-Powered Recommendation Generation"
echo "Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="C:\\Jarvis\\AI Workspace\\Apex"
cd "$PROJECT_ROOT"

echo ""
echo "Project: Apex (Next.js + TypeScript)"
echo "Service: main"
echo "Port: 3000"
echo ""

# ============================================
# ENVIRONMENT VALIDATION
# ============================================

echo "Checking environment variables..."

# Critical environment variables
if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${RED}✗ ANTHROPIC_API_KEY not set${NC}"
    echo "  Please add ANTHROPIC_API_KEY to your .env.local file"
    exit 1
else
    echo -e "${GREEN}✓ ANTHROPIC_API_KEY loaded${NC}"
fi

if [ -z "$DATABASE_URL" ]; then
    echo -e "${RED}✗ DATABASE_URL not set${NC}"
    echo "  Please add DATABASE_URL to your .env.local file"
    exit 1
else
    echo -e "${GREEN}✓ DATABASE_URL loaded${NC}"
fi

# Optional but recommended
if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${YELLOW}⚠ OPENAI_API_KEY not set (optional)${NC}"
else
    echo -e "${GREEN}✓ OPENAI_API_KEY loaded${NC}"
fi

echo ""

# ============================================
# DEPENDENCY CHECK
# ============================================

echo "Checking dependencies..."

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}⚠ node_modules not found, running npm install...${NC}"
    npm install
else
    echo -e "${GREEN}✓ node_modules exists${NC}"
fi

echo ""

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo "Starting Next.js development server..."
echo ""
echo "Service URL: http://localhost:3000"
echo "API Base: http://localhost:3000/api"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop the server${NC}"
echo ""

# Start Next.js dev server
npm run dev

# Note: This is a blocking command - the script will stay here until Ctrl+C
