/**
 * Site Audit Sub-Agent Services - Barrel Export
 */

export {
  CrawlerService,
  createCrawlerService,
  type CrawlerConfig,
  type CrawlPriority,
  type QueueItem,
  type PageMetadata,
  type LinkExtraction,
  type HeadingStructure,
  type ImageAnalysis,
  type RobotsTxtData,
  type SitemapUrl,
  type SitemapData,
  type SitemapValidation,
  type CrawlProgress,
  type CrawlError,
  type ErrorSummary,
  type PageStats,
  type CrawlStats,
  type CrawlResult,
} from './crawler-service';

export {
  TechnicalAuditService,
  createTechnicalAuditService,
  type TechnicalAuditConfig,
  type IssueSeverity,
  type IndexabilityResult,
  type CrawlabilityResult,
  type InternalLinkingResult,
  type CrawlDepthResult,
  type SSLResult,
  type MixedContentResult,
  type SecurityHeadersResult,
  type RedirectItem,
  type RedirectChainResult,
  type StatusCodeResult,
  type Soft404Result,
  type DuplicateGroup,
  type DuplicateContentResult,
  type ThinContentResult,
  type UrlAnalysisResult,
  type TechnicalIssue,
  type IssueSummary,
  type PageData,
  type RobotsData,
  type CrawlData,
  type TechnicalAuditResult,
} from './technical-audit-service';

export {
  PerformanceService,
  createPerformanceService,
  type PerformanceConfig,
  type WebVitalRating,
  type PerformanceGrade,
  type WebVitalThreshold,
  type WebVitalResult,
  type CoreWebVitals,
  type LighthouseCategories,
  type LighthouseAudit,
  type MobileDesktopComparison,
  type Resource,
  type ResourceSummary,
  type ResourceAnalysis,
  type ThirdPartyAnalysis,
  type ImageData,
  type ImageOptimizationResult,
  type OversizedImage,
  type LazyLoadingAnalysis,
  type ImageFormatRecommendation,
  type ImageRecommendations,
  type ScriptData,
  type JavaScriptAnalysis,
  type CoverageData,
  type CoverageAnalysis,
  type LongTask,
  type MainThreadBlockingAnalysis,
  type CSSAnalysis,
  type CSSCoverageAnalysis,
  type CSSRule,
  type CriticalCSSAnalysis,
} from './performance-service';

export {
  SemanticAnalysisService,
  createSemanticAnalysisService,
  type SemanticConfig,
  type SchemaOrgSchema,
  type SchemaOrgData,
  type SchemaValidationResult,
  type SemanticMarkup,
  type LandmarkRoles,
  type EntityAnalysis,
  type EntityDensity,
  type HeadingHierarchy,
  type ParagraphAnalysis,
  type ListAnalysis,
  type TableAnalysis,
  type ContentStructure,
  type ARIAAnalysis,
  type FormAccessibility,
  type ImageAccessibility,
  type TopicExtraction,
  type KeywordDensityResult,
  type KeywordStuffingResult,
  type KeyPhrase,
  type SemanticIssue,
  type PageDataForSchema,
} from './semantic-analysis-service';

export {
  AIVisibilityService,
  createAIVisibilityService,
  type AIVisibilityConfig,
  type ContentRelevanceScore,
  type TopicCoverageResult,
  type ComprehensivenessResult,
  type ContentUniquenessResult,
  type EntityOptimization,
  type EntityContextResult,
  type EntityAmbiguityResult,
  type EntityRelationship,
  type EntityRelationshipsResult,
  type EntityEnrichmentResult,
  type AIReadabilityAnalysis,
  type SentenceClarityResult,
  type FactualClaimsResult,
  type ContentFreshnessResult,
  type LLMCitationPotential,
  type QuestionAnsweringResult,
  type StructuredDataForAIResult,
  type SnippetOptimizationResult,
  type EEATResult,
  type StructuredDataOptimization,
  type SchemaEnhancementResult,
  type SchemaValidationResult as AISchemaValidationResult,
  type AIVisibilityIssue,
  type AIVisibilityRecommendation,
  type CompetitorComparison,
  type AIVisibilityResult,
} from './ai-visibility-service';

export {
  MonitoringService,
  createMonitoringService,
  type MonitoringConfig,
  type CrawlSchedule,
  type ScheduledCrawl,
  type CrawlResult as MonitoringCrawlResult,
  type CrawlCompletionData,
  type CrawlHistoryEntry,
  type SnapshotMetrics,
  type Snapshot,
  type SnapshotComparison,
  type AnomalyDetection,
  type AnomalyThreshold,
  type TrendAnalysis,
  type MetricForecast,
  type AlertConfig,
  type AlertRule,
  type Alert,
  type MonitoringReport,
  type WeeklyReport,
  type ComparisonReport,
  type HealthCheck,
  type UptimeCheck,
  type UptimeStats,
} from './monitoring-service';
