import * as dotenv from 'dotenv';
import * as path from 'path';
import { db } from '@/lib/db';
import { brands, organizations } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';

// Load .env.local for database connection
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const NEW_INDUSTRIES = {
  'Insurance / Insurtech': [
    {
      name: 'Lemonade',
      domain: 'lemonade.com',
      tagline: 'Insurance that doesn\'t suck',
      description: 'Lemonade is a digital insurance company powered by AI and behavioral economics, offering renters, homeowners, car, pet, and life insurance.',
      logoUrl: 'https://logo.clearbit.com/lemonade.com',
      industry: 'Insurance / Insurtech',
      keywords: ['lemonade', 'insurance', 'renters insurance', 'homeowners insurance', 'insurtech'],
      seoKeywords: ['digital insurance', 'AI insurance', 'renters insurance app', 'instant insurance', 'peer-to-peer insurance'],
      geoKeywords: ['lemonade insurance', 'lemonade coverage', 'lemonade claims'],
      competitors: [
        { name: 'Root Insurance', url: 'root.com', reason: 'Digital-first auto insurance' },
        { name: 'Hippo', url: 'hippo.com', reason: 'Home insurance competitor' },
        { name: 'Metromile', url: 'metromile.com', reason: 'Usage-based insurance' },
        { name: 'GEICO', url: 'geico.com', reason: 'Traditional insurance competitor' },
        { name: 'State Farm', url: 'statefarm.com', reason: 'Traditional insurance competitor' },
      ],
      valuePropositions: ['Instant everything', 'Flat fee transparency', 'Giveback program', 'AI-powered claims'],
      socialLinks: {
        twitter: 'https://twitter.com/Lemonade_Inc',
        linkedin: 'https://www.linkedin.com/company/lemonade-inc-',
        facebook: 'https://www.facebook.com/lemonade.inc',
        instagram: 'https://www.instagram.com/lemonade_inc',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['transparent', 'modern', 'customer-first', 'tech-forward'],
        targetAudience: 'Tech-savvy consumers seeking transparent, fast insurance',
        keyMessages: ['Insurance that doesn\'t suck', 'Instant everything', 'Powered by AI', 'Do good'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#FF0083',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#FF0083', '#000000', '#FFFFFF', '#FFB3D9'],
        fontFamily: 'Averta',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '5 Crosby Street',
          city: 'New York',
          state: 'NY',
          country: 'USA',
          postalCode: '10013',
        },
      ],
      personnel: [
        {
          name: 'Daniel Schreiber',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/daniel-schreiber-68001a/',
          isActive: true,
          joinedDate: '2015-04',
        },
        {
          name: 'Shai Wininger',
          title: 'Co-Founder & President',
          linkedinUrl: 'https://www.linkedin.com/in/shaiw/',
          isActive: true,
          joinedDate: '2015-04',
        },
        {
          name: 'Tim Bixby',
          title: 'CFO',
          linkedinUrl: 'https://www.linkedin.com/in/timbixby/',
          isActive: true,
          joinedDate: '2020-01',
        },
      ],
    },
    {
      name: 'Root Insurance',
      domain: 'root.com',
      tagline: 'Car insurance built for your phone',
      description: 'Root is a technology company revolutionizing personal insurance with a pricing model based primarily on fairness - rating customers based on how they actually drive.',
      logoUrl: 'https://logo.clearbit.com/root.com',
      industry: 'Insurance / Insurtech',
      keywords: ['root', 'car insurance', 'auto insurance', 'usage-based insurance', 'telematics'],
      seoKeywords: ['fair car insurance', 'driver-based insurance', 'mobile insurance app', 'telematics insurance', 'safe driver discount'],
      geoKeywords: ['root insurance', 'root auto', 'root coverage'],
      competitors: [
        { name: 'Lemonade', url: 'lemonade.com', reason: 'Insurtech competitor' },
        { name: 'Metromile', url: 'metromile.com', reason: 'Usage-based insurance' },
        { name: 'Progressive', url: 'progressive.com', reason: 'Traditional auto insurance' },
        { name: 'GEICO', url: 'geico.com', reason: 'Traditional auto insurance' },
        { name: 'Allstate', url: 'allstate.com', reason: 'Traditional auto insurance' },
      ],
      valuePropositions: ['Fair pricing based on driving', 'Mobile-first experience', 'Quick claims', 'Transparent rates'],
      socialLinks: {
        twitter: 'https://twitter.com/JoinRoot',
        linkedin: 'https://www.linkedin.com/company/root-insurance-company',
        facebook: 'https://www.facebook.com/JoinRoot',
        instagram: 'https://www.instagram.com/joinroot',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['fair', 'transparent', 'data-driven', 'customer-centric'],
        targetAudience: 'Good drivers seeking fair insurance pricing',
        keyMessages: ['Fair insurance', 'Based on driving', 'Mobile-first', 'Rewarding good drivers'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#000000',
        secondaryColor: '#FFFFFF',
        accentColor: '#00D4B4',
        colorPalette: ['#000000', '#FFFFFF', '#00D4B4', '#333333'],
        fontFamily: 'GT America',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '80 E Rich St',
          city: 'Columbus',
          state: 'OH',
          country: 'USA',
          postalCode: '43215',
        },
      ],
      personnel: [
        {
          name: 'Alex Timm',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/alextimm/',
          isActive: true,
          joinedDate: '2015-02',
        },
        {
          name: 'Dan Manges',
          title: 'Co-Founder & CTO',
          linkedinUrl: 'https://www.linkedin.com/in/danmanges/',
          isActive: true,
          joinedDate: '2015-02',
        },
      ],
    },
    {
      name: 'PolicyGenius',
      domain: 'policygenius.com',
      tagline: 'Compare and buy insurance online',
      description: 'PolicyGenius is an insurance marketplace that makes it easy to compare quotes and buy life insurance, home insurance, auto insurance, and more.',
      logoUrl: 'https://logo.clearbit.com/policygenius.com',
      industry: 'Insurance / Insurtech',
      keywords: ['policygenius', 'insurance marketplace', 'life insurance', 'compare insurance', 'insurance quotes'],
      seoKeywords: ['insurance comparison', 'online insurance quotes', 'life insurance calculator', 'term life insurance', 'insurance marketplace'],
      geoKeywords: ['policygenius reviews', 'policygenius life insurance', 'policygenius quotes'],
      competitors: [
        { name: 'Ladder', url: 'ladderlife.com', reason: 'Digital life insurance' },
        { name: 'Haven Life', url: 'havenlife.com', reason: 'Online life insurance' },
        { name: 'Quotacy', url: 'quotacy.com', reason: 'Insurance comparison' },
        { name: 'Ethos', url: 'ethoslife.com', reason: 'Digital life insurance' },
        { name: 'Bestow', url: 'hellobestow.com', reason: 'Online life insurance' },
      ],
      valuePropositions: ['Unbiased advice', 'Easy comparison', 'Expert guidance', 'All insurance types'],
      socialLinks: {
        twitter: 'https://twitter.com/policygenius',
        linkedin: 'https://www.linkedin.com/company/policygenius',
        facebook: 'https://www.facebook.com/policygenius',
        instagram: 'https://www.instagram.com/policygenius',
      },
      voice: {
        tone: 'helpful' as const,
        personality: ['educational', 'trustworthy', 'straightforward', 'empowering'],
        targetAudience: 'Consumers researching and comparing insurance options',
        keyMessages: ['Unbiased advice', 'Easy comparison', 'Expert help', 'All in one place'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#0F74F0',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#0F74F0', '#1A1A1A', '#FFFFFF', '#66A3F5'],
        fontFamily: 'Source Sans Pro',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '450 7th Ave',
          city: 'New York',
          state: 'NY',
          country: 'USA',
          postalCode: '10123',
        },
      ],
      personnel: [
        {
          name: 'Jennifer Fitzgerald',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/jenniferfitzgerald/',
          isActive: true,
          joinedDate: '2014-05',
        },
        {
          name: 'Francois de Lame',
          title: 'Co-Founder & Chief of Staff',
          linkedinUrl: 'https://www.linkedin.com/in/francoisdelame/',
          isActive: true,
          joinedDate: '2014-05',
        },
      ],
    },
    {
      name: 'Oscar Health',
      domain: 'hioscar.com',
      tagline: 'Health insurance that actually helps',
      description: 'Oscar is a health insurance company that uses technology to humanize healthcare, offering individual, small group, and Medicare Advantage plans.',
      logoUrl: 'https://logo.clearbit.com/hioscar.com',
      industry: 'Insurance / Insurtech',
      keywords: ['oscar health', 'health insurance', 'medical insurance', 'healthcare', 'insurance technology'],
      seoKeywords: ['affordable health insurance', 'individual health insurance', 'family health insurance', 'medicare advantage', 'health insurance marketplace'],
      geoKeywords: ['oscar health insurance', 'oscar coverage', 'oscar plans'],
      competitors: [
        { name: 'Bright Health', url: 'brighthealthplan.com', reason: 'Health insurance competitor' },
        { name: 'Clover Health', url: 'cloverhealth.com', reason: 'Medicare Advantage competitor' },
        { name: 'Blue Cross Blue Shield', url: 'bcbs.com', reason: 'Traditional health insurance' },
        { name: 'UnitedHealthcare', url: 'uhc.com', reason: 'Traditional health insurance' },
        { name: 'Aetna', url: 'aetna.com', reason: 'Traditional health insurance' },
      ],
      valuePropositions: ['Simple plans', '24/7 doctor access', 'Personalized care', 'Easy claims'],
      socialLinks: {
        twitter: 'https://twitter.com/OscarHealth',
        linkedin: 'https://www.linkedin.com/company/oscar-health',
        facebook: 'https://www.facebook.com/hiOscar',
        instagram: 'https://www.instagram.com/hioscar',
      },
      voice: {
        tone: 'empowering' as const,
        personality: ['caring', 'transparent', 'modern', 'accessible'],
        targetAudience: 'Individuals and families seeking better health insurance experience',
        keyMessages: ['Health insurance that helps', 'Simple and transparent', 'Care team support', 'Technology-enabled'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#2D9CDB',
        secondaryColor: '#27AE60',
        accentColor: '#FFFFFF',
        colorPalette: ['#2D9CDB', '#27AE60', '#FFFFFF', '#85C9E8'],
        fontFamily: 'Circular',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '75 Varick St',
          city: 'New York',
          state: 'NY',
          country: 'USA',
          postalCode: '10013',
        },
      ],
      personnel: [
        {
          name: 'Mark Bertolini',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/mark-bertolini-0b5b1b1/',
          isActive: true,
          joinedDate: '2021-03',
        },
        {
          name: 'Mario Schlosser',
          title: 'Co-Founder & CTO',
          linkedinUrl: 'https://www.linkedin.com/in/marioschlosser/',
          isActive: true,
          joinedDate: '2012-11',
        },
      ],
    },
    {
      name: 'Next Insurance',
      domain: 'nextinsurance.com',
      tagline: 'Small business insurance made simple',
      description: 'Next Insurance provides tailored insurance solutions for small businesses with instant quotes, simple online purchasing, and affordable coverage.',
      logoUrl: 'https://logo.clearbit.com/nextinsurance.com',
      industry: 'Insurance / Insurtech',
      keywords: ['next insurance', 'small business insurance', 'liability insurance', 'business insurance', 'commercial insurance'],
      seoKeywords: ['small business insurance online', 'general liability insurance', 'professional liability', 'workers compensation', 'business insurance quotes'],
      geoKeywords: ['next insurance reviews', 'next insurance coverage', 'next insurance cost'],
      competitors: [
        { name: 'Hiscox', url: 'hiscox.com', reason: 'Small business insurance' },
        { name: 'CoverWallet', url: 'coverwallet.com', reason: 'Business insurance platform' },
        { name: 'Pie Insurance', url: 'pieinsurance.com', reason: 'Workers comp insurance' },
        { name: 'The Hartford', url: 'thehartford.com', reason: 'Traditional business insurance' },
        { name: 'Nationwide', url: 'nationwide.com', reason: 'Traditional business insurance' },
      ],
      valuePropositions: ['Instant quotes', 'Affordable coverage', 'Tailored policies', 'Easy online purchase'],
      socialLinks: {
        twitter: 'https://twitter.com/NextInsurance',
        linkedin: 'https://www.linkedin.com/company/next-insurance',
        facebook: 'https://www.facebook.com/NextInsurance',
        instagram: 'https://www.instagram.com/nextinsurance',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['straightforward', 'supportive', 'efficient', 'small-business-focused'],
        targetAudience: 'Small business owners seeking simple, affordable insurance',
        keyMessages: ['Built for small business', 'Simple and fast', 'Affordable coverage', 'Expert support'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#5B3EE5',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#5B3EE5', '#1A1A1A', '#FFFFFF', '#9B8DF0'],
        fontFamily: 'Inter',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '525 Brannan St',
          city: 'Palo Alto',
          state: 'CA',
          country: 'USA',
          postalCode: '94301',
        },
      ],
      personnel: [
        {
          name: 'Guy Goldstein',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/guy-goldstein-66a6a21/',
          isActive: true,
          joinedDate: '2016-01',
        },
        {
          name: 'Alon Huri',
          title: 'Co-Founder & CTO',
          linkedinUrl: 'https://www.linkedin.com/in/alonhuri/',
          isActive: true,
          joinedDate: '2016-01',
        },
      ],
    },
  ],
  'HR / Recruitment Tech': [
    {
      name: 'LinkedIn',
      domain: 'linkedin.com',
      tagline: 'Welcome to your professional community',
      description: 'LinkedIn is the world\'s largest professional network with over 900 million members, offering networking, job searching, recruiting, and professional development.',
      logoUrl: 'https://logo.clearbit.com/linkedin.com',
      industry: 'HR / Recruitment Tech',
      keywords: ['linkedin', 'professional networking', 'job search', 'recruiting', 'hiring'],
      seoKeywords: ['professional network', 'job opportunities', 'career development', 'business networking', 'talent acquisition'],
      geoKeywords: ['linkedin jobs', 'linkedin recruiter', 'linkedin premium'],
      competitors: [
        { name: 'Indeed', url: 'indeed.com', reason: 'Job search competitor' },
        { name: 'Glassdoor', url: 'glassdoor.com', reason: 'Job search and reviews' },
        { name: 'ZipRecruiter', url: 'ziprecruiter.com', reason: 'Recruiting platform' },
        { name: 'Monster', url: 'monster.com', reason: 'Job board competitor' },
        { name: 'CareerBuilder', url: 'careerbuilder.com', reason: 'Job board competitor' },
      ],
      valuePropositions: ['Largest professional network', 'Job opportunities', 'Business insights', 'Learning and development'],
      socialLinks: {
        twitter: 'https://twitter.com/LinkedIn',
        linkedin: 'https://www.linkedin.com/company/linkedin',
        facebook: 'https://www.facebook.com/LinkedIn',
        instagram: 'https://www.instagram.com/linkedin',
        youtube: 'https://www.youtube.com/c/linkedin',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['authoritative', 'professional', 'empowering', 'career-focused'],
        targetAudience: 'Professionals seeking career growth and business connections',
        keyMessages: ['Professional community', 'Career opportunities', 'Business networking', 'Professional growth'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#0A66C2',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#0A66C2', '#000000', '#FFFFFF', '#378FE9'],
        fontFamily: 'Helvetica Neue',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '1000 W Maude Ave',
          city: 'Sunnyvale',
          state: 'CA',
          country: 'USA',
          postalCode: '94085',
        },
      ],
      personnel: [
        {
          name: 'Ryan Roslansky',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/ryanroslansky/',
          isActive: true,
          joinedDate: '2020-06',
        },
        {
          name: 'Tomer Cohen',
          title: 'Chief Product Officer',
          linkedinUrl: 'https://www.linkedin.com/in/tomercohen/',
          isActive: true,
          joinedDate: '2016-01',
        },
      ],
    },
    {
      name: 'Greenhouse',
      domain: 'greenhouse.io',
      tagline: 'Hire for what\'s next',
      description: 'Greenhouse is a recruiting software company that helps businesses become great at hiring through structured hiring, data-driven insights, and fair hiring practices.',
      logoUrl: 'https://logo.clearbit.com/greenhouse.io',
      industry: 'HR / Recruitment Tech',
      keywords: ['greenhouse', 'recruiting software', 'applicant tracking', 'hiring platform', 'recruitment'],
      seoKeywords: ['ATS software', 'recruiting platform', 'hiring software', 'talent acquisition software', 'interview scheduling'],
      geoKeywords: ['greenhouse ats', 'greenhouse software', 'greenhouse recruiting'],
      competitors: [
        { name: 'Lever', url: 'lever.co', reason: 'Recruiting software competitor' },
        { name: 'Workable', url: 'workable.com', reason: 'Hiring platform competitor' },
        { name: 'SmartRecruiters', url: 'smartrecruiters.com', reason: 'Talent acquisition platform' },
        { name: 'iCIMS', url: 'icims.com', reason: 'Enterprise ATS competitor' },
        { name: 'Jobvite', url: 'jobvite.com', reason: 'Recruiting software competitor' },
      ],
      valuePropositions: ['Structured hiring', 'Fair hiring practices', 'Data-driven insights', 'Seamless integrations'],
      socialLinks: {
        twitter: 'https://twitter.com/greenhouse',
        linkedin: 'https://www.linkedin.com/company/greenhouse-inc-',
        facebook: 'https://www.facebook.com/greenhouse.io',
        instagram: 'https://www.instagram.com/greenhouse_io',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['thoughtful', 'data-driven', 'fair', 'innovative'],
        targetAudience: 'HR teams and hiring managers seeking better recruiting processes',
        keyMessages: ['Structured hiring', 'Fair and equitable', 'Data-driven decisions', 'Great at hiring'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#15B869',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#15B869', '#1A1A1A', '#FFFFFF', '#5DD999'],
        fontFamily: 'Graphik',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '18 West 18th Street',
          city: 'New York',
          state: 'NY',
          country: 'USA',
          postalCode: '10011',
        },
      ],
      personnel: [
        {
          name: 'Daniel Chait',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/danielchait/',
          isActive: true,
          joinedDate: '2012-01',
        },
        {
          name: 'Jon Stross',
          title: 'Co-Founder & President',
          linkedinUrl: 'https://www.linkedin.com/in/jonstross/',
          isActive: true,
          joinedDate: '2012-01',
        },
      ],
    },
    {
      name: 'Workday',
      domain: 'workday.com',
      tagline: 'The finance, HR, and planning system for a changing world',
      description: 'Workday is a leading provider of enterprise cloud applications for finance, HR, and planning, helping organizations adapt and thrive in a changing world.',
      logoUrl: 'https://logo.clearbit.com/workday.com',
      industry: 'HR / Recruitment Tech',
      keywords: ['workday', 'HRIS', 'human capital management', 'enterprise software', 'HR software'],
      seoKeywords: ['human capital management', 'enterprise HR software', 'workforce planning', 'payroll software', 'talent management'],
      geoKeywords: ['workday hcm', 'workday software', 'workday login'],
      competitors: [
        { name: 'SAP SuccessFactors', url: 'sap.com/successfactors', reason: 'Enterprise HCM competitor' },
        { name: 'Oracle HCM', url: 'oracle.com/hcm', reason: 'Enterprise HR software' },
        { name: 'ADP', url: 'adp.com', reason: 'Payroll and HR services' },
        { name: 'UKG', url: 'ukg.com', reason: 'Workforce management competitor' },
        { name: 'BambooHR', url: 'bamboohr.com', reason: 'SMB HR software' },
      ],
      valuePropositions: ['Unified system', 'AI and ML insights', 'Continuous innovation', 'Enterprise scale'],
      socialLinks: {
        twitter: 'https://twitter.com/Workday',
        linkedin: 'https://www.linkedin.com/company/workday',
        facebook: 'https://www.facebook.com/workday',
        instagram: 'https://www.instagram.com/workday',
        youtube: 'https://www.youtube.com/c/workday',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['innovative', 'reliable', 'enterprise-focused', 'forward-thinking'],
        targetAudience: 'Enterprise organizations seeking unified finance and HR systems',
        keyMessages: ['Built for change', 'Unified platform', 'Enterprise-grade', 'Innovation-driven'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#EB0028',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#EB0028', '#1A1A1A', '#FFFFFF', '#F5334D'],
        fontFamily: 'Workday Sans',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '6110 Stoneridge Mall Rd',
          city: 'Pleasanton',
          state: 'CA',
          country: 'USA',
          postalCode: '94588',
        },
      ],
      personnel: [
        {
          name: 'Carl Eschenbach',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/carleschenbach/',
          isActive: true,
          joinedDate: '2023-01',
        },
        {
          name: 'Aneel Bhusri',
          title: 'Co-Founder & Executive Chairman',
          linkedinUrl: 'https://www.linkedin.com/in/aneelbhusri/',
          isActive: true,
          joinedDate: '2005-03',
        },
      ],
    },
    {
      name: 'BambooHR',
      domain: 'bamboohr.com',
      tagline: 'HR software for small and medium-sized businesses',
      description: 'BambooHR is an all-in-one HR software platform designed for small and medium-sized businesses, offering employee records, hiring, onboarding, and culture tools.',
      logoUrl: 'https://logo.clearbit.com/bamboohr.com',
      industry: 'HR / Recruitment Tech',
      keywords: ['bamboohr', 'HR software', 'HRIS', 'employee management', 'small business HR'],
      seoKeywords: ['small business HR software', 'employee database', 'onboarding software', 'time off tracking', 'performance management'],
      geoKeywords: ['bamboohr pricing', 'bamboohr reviews', 'bamboohr features'],
      competitors: [
        { name: 'Gusto', url: 'gusto.com', reason: 'Payroll and HR for SMB' },
        { name: 'Namely', url: 'namely.com', reason: 'Mid-market HR platform' },
        { name: 'Rippling', url: 'rippling.com', reason: 'All-in-one HR platform' },
        { name: 'Zenefits', url: 'zenefits.com', reason: 'SMB HR software' },
        { name: 'Paycor', url: 'paycor.com', reason: 'HR and payroll software' },
      ],
      valuePropositions: ['Easy to use', 'Affordable for SMB', 'All-in-one platform', 'Great support'],
      socialLinks: {
        twitter: 'https://twitter.com/bamboohr',
        linkedin: 'https://www.linkedin.com/company/bamboohr',
        facebook: 'https://www.facebook.com/bamboohr',
        instagram: 'https://www.instagram.com/bamboohr',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['approachable', 'supportive', 'SMB-focused', 'culture-driven'],
        targetAudience: 'Small and medium-sized businesses seeking simple HR solutions',
        keyMessages: ['Built for SMB', 'Easy to use', 'People-first culture', 'All-in-one HR'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#73C41D',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#73C41D', '#1A1A1A', '#FFFFFF', '#A0DC5C'],
        fontFamily: 'Open Sans',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '2010 Prospector Ave',
          city: 'Park City',
          state: 'UT',
          country: 'USA',
          postalCode: '84060',
        },
      ],
      personnel: [
        {
          name: 'Brad Rencher',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/bradrencher/',
          isActive: true,
          joinedDate: '2017-01',
        },
        {
          name: 'Ben Peterson',
          title: 'Co-Founder & VP of Product',
          linkedinUrl: 'https://www.linkedin.com/in/ben-peterson-bamboohr/',
          isActive: true,
          joinedDate: '2008-01',
        },
      ],
    },
    {
      name: 'Gusto',
      domain: 'gusto.com',
      tagline: 'Payroll, benefits, and HR for modern teams',
      description: 'Gusto is a modern, online people platform that helps small businesses take care of their teams with full-service payroll, benefits, HR, and more.',
      logoUrl: 'https://logo.clearbit.com/gusto.com',
      industry: 'HR / Recruitment Tech',
      keywords: ['gusto', 'payroll', 'benefits', 'HR software', 'small business payroll'],
      seoKeywords: ['online payroll', 'payroll software', 'employee benefits', 'HR management', 'small business HR'],
      geoKeywords: ['gusto payroll', 'gusto pricing', 'gusto reviews'],
      competitors: [
        { name: 'ADP', url: 'adp.com', reason: 'Payroll services competitor' },
        { name: 'Paychex', url: 'paychex.com', reason: 'Payroll and HR services' },
        { name: 'Rippling', url: 'rippling.com', reason: 'All-in-one HR platform' },
        { name: 'Zenefits', url: 'zenefits.com', reason: 'HR and benefits platform' },
        { name: 'Justworks', url: 'justworks.com', reason: 'PEO and payroll competitor' },
      ],
      valuePropositions: ['Easy payroll', 'Integrated benefits', 'Modern platform', 'Expert support'],
      socialLinks: {
        twitter: 'https://twitter.com/gustohq',
        linkedin: 'https://www.linkedin.com/company/gusto-inc',
        facebook: 'https://www.facebook.com/gustohq',
        instagram: 'https://www.instagram.com/gustohq',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['caring', 'modern', 'supportive', 'team-focused'],
        targetAudience: 'Small businesses seeking simple payroll and benefits management',
        keyMessages: ['Built for modern teams', 'Easy to use', 'People-first', 'Full-service'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#F45D48',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#F45D48', '#1A1A1A', '#FFFFFF', '#F89083'],
        fontFamily: 'Basis Grotesque Pro',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '525 20th St',
          city: 'San Francisco',
          state: 'CA',
          country: 'USA',
          postalCode: '94107',
        },
      ],
      personnel: [
        {
          name: 'Josh Reeves',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/joshreeves/',
          isActive: true,
          joinedDate: '2011-11',
        },
        {
          name: 'Tomer London',
          title: 'Co-Founder & CPO',
          linkedinUrl: 'https://www.linkedin.com/in/tomerlondon/',
          isActive: true,
          joinedDate: '2011-11',
        },
      ],
    },
  ],
  'Cybersecurity': [
    {
      name: 'CrowdStrike',
      domain: 'crowdstrike.com',
      tagline: 'Stop breaches. Drive business.',
      description: 'CrowdStrike is a global cybersecurity leader providing cloud-delivered endpoint and workload protection through the CrowdStrike Falcon platform.',
      logoUrl: 'https://logo.clearbit.com/crowdstrike.com',
      industry: 'Cybersecurity',
      keywords: ['crowdstrike', 'endpoint protection', 'cybersecurity', 'threat intelligence', 'cloud security'],
      seoKeywords: ['endpoint security', 'EDR solution', 'threat detection', 'incident response', 'cyber threat intelligence'],
      geoKeywords: ['crowdstrike falcon', 'crowdstrike pricing', 'crowdstrike vs competitors'],
      competitors: [
        { name: 'Palo Alto Networks', url: 'paloaltonetworks.com', reason: 'Cybersecurity competitor' },
        { name: 'SentinelOne', url: 'sentinelone.com', reason: 'Endpoint protection competitor' },
        { name: 'Carbon Black', url: 'carbonblack.com', reason: 'EDR competitor' },
        { name: 'Microsoft Defender', url: 'microsoft.com/defender', reason: 'Endpoint security competitor' },
        { name: 'Sophos', url: 'sophos.com', reason: 'Cybersecurity competitor' },
      ],
      valuePropositions: ['Cloud-native platform', 'AI-powered protection', 'Single agent architecture', 'Real-time threat intelligence'],
      socialLinks: {
        twitter: 'https://twitter.com/CrowdStrike',
        linkedin: 'https://www.linkedin.com/company/crowdstrike',
        facebook: 'https://www.facebook.com/CrowdStrike',
        instagram: 'https://www.instagram.com/crowdstrike',
        youtube: 'https://www.youtube.com/c/CrowdStrike',
      },
      voice: {
        tone: 'authoritative' as const,
        personality: ['protective', 'innovative', 'vigilant', 'expert'],
        targetAudience: 'Enterprises seeking advanced endpoint protection and threat intelligence',
        keyMessages: ['Stop breaches', 'Cloud-native', 'AI-powered', 'We stop breaches'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#FF0000',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#FF0000', '#000000', '#FFFFFF', '#FF4D4D'],
        fontFamily: 'Proxima Nova',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '150 Mathilda Place',
          city: 'Sunnyvale',
          state: 'CA',
          country: 'USA',
          postalCode: '94086',
        },
      ],
      personnel: [
        {
          name: 'George Kurtz',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/george-kurtz/',
          isActive: true,
          joinedDate: '2011-11',
        },
        {
          name: 'Dmitri Alperovitch',
          title: 'Co-Founder & Former CTO',
          linkedinUrl: 'https://www.linkedin.com/in/dmitri-alperovitch/',
          isActive: false,
          joinedDate: '2011-11',
        },
      ],
    },
    {
      name: 'Palo Alto Networks',
      domain: 'paloaltonetworks.com',
      tagline: 'Securing your digital way of life',
      description: 'Palo Alto Networks is a global cybersecurity leader, providing next-generation firewalls, cloud security, and endpoint protection to secure enterprise networks.',
      logoUrl: 'https://logo.clearbit.com/paloaltonetworks.com',
      industry: 'Cybersecurity',
      keywords: ['palo alto networks', 'firewall', 'network security', 'cloud security', 'cybersecurity platform'],
      seoKeywords: ['next-generation firewall', 'network security platform', 'cloud-delivered security', 'zero trust', 'threat prevention'],
      geoKeywords: ['palo alto firewall', 'palo alto networks', 'palo alto security'],
      competitors: [
        { name: 'Fortinet', url: 'fortinet.com', reason: 'Network security competitor' },
        { name: 'Check Point', url: 'checkpoint.com', reason: 'Firewall competitor' },
        { name: 'Cisco Security', url: 'cisco.com', reason: 'Network security competitor' },
        { name: 'CrowdStrike', url: 'crowdstrike.com', reason: 'Cybersecurity competitor' },
        { name: 'Zscaler', url: 'zscaler.com', reason: 'Cloud security competitor' },
      ],
      valuePropositions: ['Comprehensive platform', 'AI-driven security', 'Cloud-delivered', 'Zero trust architecture'],
      socialLinks: {
        twitter: 'https://twitter.com/PaloAltoNtwks',
        linkedin: 'https://www.linkedin.com/company/palo-alto-networks',
        facebook: 'https://www.facebook.com/PaloAltoNetworks',
        instagram: 'https://www.instagram.com/paloaltonetworks',
        youtube: 'https://www.youtube.com/c/PaloAltoNetworks',
      },
      voice: {
        tone: 'authoritative' as const,
        personality: ['innovative', 'protective', 'enterprise-focused', 'comprehensive'],
        targetAudience: 'Enterprises seeking comprehensive network and cloud security',
        keyMessages: ['Secure digital life', 'Platform approach', 'Innovation-driven', 'Zero trust'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#FA582D',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#FA582D', '#000000', '#FFFFFF', '#FC8A6E'],
        fontFamily: 'Montserrat',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '3000 Tannery Way',
          city: 'Santa Clara',
          state: 'CA',
          country: 'USA',
          postalCode: '95054',
        },
      ],
      personnel: [
        {
          name: 'Nikesh Arora',
          title: 'Chairman & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/nikesharora/',
          isActive: true,
          joinedDate: '2018-06',
        },
        {
          name: 'Nir Zuk',
          title: 'Founder & CTO',
          linkedinUrl: 'https://www.linkedin.com/in/nirzuk/',
          isActive: true,
          joinedDate: '2005-01',
        },
      ],
    },
    {
      name: '1Password',
      domain: '1password.com',
      tagline: 'Go ahead. Forget your passwords.',
      description: '1Password is a password manager that provides a secure and convenient solution for individuals, families, and businesses to store and manage passwords and sensitive information.',
      logoUrl: 'https://logo.clearbit.com/1password.com',
      industry: 'Cybersecurity',
      keywords: ['1password', 'password manager', 'password security', 'credential management', 'secrets management'],
      seoKeywords: ['best password manager', 'secure password storage', 'password vault', 'team password manager', 'business password manager'],
      geoKeywords: ['1password pricing', '1password vs lastpass', '1password families'],
      competitors: [
        { name: 'LastPass', url: 'lastpass.com', reason: 'Password manager competitor' },
        { name: 'Dashlane', url: 'dashlane.com', reason: 'Password manager competitor' },
        { name: 'Bitwarden', url: 'bitwarden.com', reason: 'Open-source password manager' },
        { name: 'Keeper', url: 'keepersecurity.com', reason: 'Password security competitor' },
        { name: 'NordPass', url: 'nordpass.com', reason: 'Password manager competitor' },
      ],
      valuePropositions: ['Easy to use', 'Secure by design', 'Family and business plans', 'Cross-platform'],
      socialLinks: {
        twitter: 'https://twitter.com/1Password',
        linkedin: 'https://www.linkedin.com/company/1password',
        facebook: 'https://www.facebook.com/1Password',
        instagram: 'https://www.instagram.com/1passwordapp',
        youtube: 'https://www.youtube.com/c/1PasswordVideos',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['helpful', 'security-focused', 'user-friendly', 'trustworthy'],
        targetAudience: 'Individuals, families, and businesses seeking secure password management',
        keyMessages: ['Forget passwords', 'Security made simple', 'Trusted by millions', 'All your passwords'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#0094F5',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#0094F5', '#1A1A1A', '#FFFFFF', '#4DB8F8'],
        fontFamily: 'Inter',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '100 Adelaide Street West',
          city: 'Toronto',
          state: 'ON',
          country: 'Canada',
          postalCode: 'M5H 1S3',
        },
      ],
      personnel: [
        {
          name: 'Jeff Shiner',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/jeffshiner/',
          isActive: true,
          joinedDate: '2012-01',
        },
        {
          name: 'Dave Teare',
          title: 'Founder',
          linkedinUrl: 'https://www.linkedin.com/in/dteare/',
          isActive: true,
          joinedDate: '2005-06',
        },
      ],
    },
    {
      name: 'Norton',
      domain: 'norton.com',
      tagline: 'Device security for your digital life',
      description: 'Norton is a global leader in consumer cybersecurity, providing antivirus, VPN, password manager, and identity protection solutions for individuals and families.',
      logoUrl: 'https://logo.clearbit.com/norton.com',
      industry: 'Cybersecurity',
      keywords: ['norton', 'antivirus', 'internet security', 'device protection', 'vpn'],
      seoKeywords: ['antivirus software', 'internet security suite', 'malware protection', 'identity theft protection', 'secure VPN'],
      geoKeywords: ['norton 360', 'norton antivirus', 'norton security'],
      competitors: [
        { name: 'McAfee', url: 'mcafee.com', reason: 'Consumer security competitor' },
        { name: 'Bitdefender', url: 'bitdefender.com', reason: 'Antivirus competitor' },
        { name: 'Kaspersky', url: 'kaspersky.com', reason: 'Security software competitor' },
        { name: 'Avast', url: 'avast.com', reason: 'Antivirus competitor' },
        { name: 'Trend Micro', url: 'trendmicro.com', reason: 'Security software competitor' },
      ],
      valuePropositions: ['Comprehensive protection', 'Identity protection', 'VPN included', 'Trusted brand'],
      socialLinks: {
        twitter: 'https://twitter.com/NortonOnline',
        linkedin: 'https://www.linkedin.com/company/norton',
        facebook: 'https://www.facebook.com/Norton',
        instagram: 'https://www.instagram.com/nortonlifelock',
        youtube: 'https://www.youtube.com/c/Norton',
      },
      voice: {
        tone: 'reassuring' as const,
        personality: ['protective', 'trustworthy', 'established', 'consumer-focused'],
        targetAudience: 'Consumers seeking comprehensive device and identity protection',
        keyMessages: ['Trusted protection', 'Digital life security', 'Peace of mind', 'Proven security'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#FFC800',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#FFC800', '#000000', '#FFFFFF', '#FFD84D'],
        fontFamily: 'Nunito Sans',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '60 E Rio Salado Pkwy',
          city: 'Tempe',
          state: 'AZ',
          country: 'USA',
          postalCode: '85281',
        },
      ],
      personnel: [
        {
          name: 'Vincent Pilette',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/vincent-pilette/',
          isActive: true,
          joinedDate: '2022-09',
        },
      ],
    },
    {
      name: 'Okta',
      domain: 'okta.com',
      tagline: 'The identity company',
      description: 'Okta is a leading independent identity provider, offering secure identity and access management solutions that connect people to technology in a simple and secure way.',
      logoUrl: 'https://logo.clearbit.com/okta.com',
      industry: 'Cybersecurity',
      keywords: ['okta', 'identity management', 'access management', 'SSO', 'authentication'],
      seoKeywords: ['identity and access management', 'single sign-on', 'multi-factor authentication', 'identity provider', 'zero trust security'],
      geoKeywords: ['okta sso', 'okta authentication', 'okta identity'],
      competitors: [
        { name: 'Auth0', url: 'auth0.com', reason: 'Identity platform competitor' },
        { name: 'Ping Identity', url: 'pingidentity.com', reason: 'IAM competitor' },
        { name: 'Microsoft Entra ID', url: 'microsoft.com/entra', reason: 'Identity management competitor' },
        { name: 'OneLogin', url: 'onelogin.com', reason: 'SSO competitor' },
        { name: 'ForgeRock', url: 'forgerock.com', reason: 'Identity platform competitor' },
      ],
      valuePropositions: ['Independent identity', 'Seamless access', 'Zero trust security', 'Developer-friendly'],
      socialLinks: {
        twitter: 'https://twitter.com/okta',
        linkedin: 'https://www.linkedin.com/company/okta-inc-',
        facebook: 'https://www.facebook.com/OktaInc',
        instagram: 'https://www.instagram.com/okta',
        youtube: 'https://www.youtube.com/c/OktaInc',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['innovative', 'secure', 'developer-focused', 'enterprise-ready'],
        targetAudience: 'Enterprises seeking comprehensive identity and access management',
        keyMessages: ['Always-on identity', 'Secure connections', 'Zero trust', 'Identity for all'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#007DC1',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#007DC1', '#000000', '#FFFFFF', '#4DA8D9'],
        fontFamily: 'Aeonik',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '100 First Street',
          city: 'San Francisco',
          state: 'CA',
          country: 'USA',
          postalCode: '94105',
        },
      ],
      personnel: [
        {
          name: 'Todd McKinnon',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/toddmckinnon/',
          isActive: true,
          joinedDate: '2009-01',
        },
        {
          name: 'Frederic Kerrest',
          title: 'Co-Founder & COO',
          linkedinUrl: 'https://www.linkedin.com/in/fkerrest/',
          isActive: true,
          joinedDate: '2009-01',
        },
      ],
    },
  ],
  'Legal / Legal Tech': [
    {
      name: 'LegalZoom',
      domain: 'legalzoom.com',
      tagline: 'Legal help is here',
      description: 'LegalZoom is a leading online legal technology company providing legal documents, business formation services, and access to attorneys for individuals and small businesses.',
      logoUrl: 'https://logo.clearbit.com/legalzoom.com',
      industry: 'Legal / Legal Tech',
      keywords: ['legalzoom', 'legal documents', 'business formation', 'legal services', 'online legal'],
      seoKeywords: ['LLC formation', 'legal documents online', 'trademark registration', 'will and testament', 'business incorporation'],
      geoKeywords: ['legalzoom llc', 'legalzoom reviews', 'legalzoom pricing'],
      competitors: [
        { name: 'Rocket Lawyer', url: 'rocketlawyer.com', reason: 'Online legal services competitor' },
        { name: 'Incfile', url: 'incfile.com', reason: 'Business formation competitor' },
        { name: 'Northwest Registered Agent', url: 'northwestregisteredagent.com', reason: 'Business formation competitor' },
        { name: 'ZenBusiness', url: 'zenbusiness.com', reason: 'Business formation competitor' },
        { name: 'Nolo', url: 'nolo.com', reason: 'Legal information and documents' },
      ],
      valuePropositions: ['Affordable legal help', 'Easy online process', 'Attorney access', 'Trusted since 2001'],
      socialLinks: {
        twitter: 'https://twitter.com/LegalZoom',
        linkedin: 'https://www.linkedin.com/company/legalzoom-com',
        facebook: 'https://www.facebook.com/LegalZoom',
        instagram: 'https://www.instagram.com/legalzoom',
        youtube: 'https://www.youtube.com/c/LegalZoom',
      },
      voice: {
        tone: 'helpful' as const,
        personality: ['accessible', 'trustworthy', 'supportive', 'empowering'],
        targetAudience: 'Individuals and small businesses seeking affordable legal services',
        keyMessages: ['Legal help is here', 'Affordable legal', 'Easy online', 'Expert support'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#F37021',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#F37021', '#1A1A1A', '#FFFFFF', '#F69961'],
        fontFamily: 'Proxima Nova',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '101 N Brand Blvd',
          city: 'Glendale',
          state: 'CA',
          country: 'USA',
          postalCode: '91203',
        },
      ],
      personnel: [
        {
          name: 'Dan Wernikoff',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/danwernikoff/',
          isActive: true,
          joinedDate: '2021-01',
        },
      ],
    },
    {
      name: 'Clio',
      domain: 'clio.com',
      tagline: 'The legal operating system',
      description: 'Clio is a cloud-based legal practice management software that helps law firms manage cases, clients, documents, billing, and more in one integrated platform.',
      logoUrl: 'https://logo.clearbit.com/clio.com',
      industry: 'Legal / Legal Tech',
      keywords: ['clio', 'legal practice management', 'law firm software', 'case management', 'legal billing'],
      seoKeywords: ['legal practice management software', 'law firm case management', 'legal billing software', 'client intake software', 'legal document management'],
      geoKeywords: ['clio manage', 'clio grow', 'clio accounting'],
      competitors: [
        { name: 'MyCase', url: 'mycase.com', reason: 'Practice management competitor' },
        { name: 'PracticePanther', url: 'practicepanther.com', reason: 'Law firm software competitor' },
        { name: 'Smokeball', url: 'smokeball.com', reason: 'Legal practice management' },
        { name: 'CosmoLex', url: 'cosmolex.com', reason: 'Legal software competitor' },
        { name: 'Rocket Matter', url: 'rocketmatter.com', reason: 'Practice management competitor' },
      ],
      valuePropositions: ['All-in-one platform', 'Cloud-based', 'Integrations ecosystem', 'Industry leader'],
      socialLinks: {
        twitter: 'https://twitter.com/clio',
        linkedin: 'https://www.linkedin.com/company/clio',
        facebook: 'https://www.facebook.com/goclio',
        instagram: 'https://www.instagram.com/goclio',
        youtube: 'https://www.youtube.com/c/ClioLegalSoftware',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['innovative', 'lawyer-focused', 'reliable', 'modern'],
        targetAudience: 'Law firms seeking comprehensive practice management solutions',
        keyMessages: ['Legal operating system', 'Transform your practice', 'Cloud-based', 'Built for lawyers'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#00B8D4',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#00B8D4', '#1A1A1A', '#FFFFFF', '#4DD0E8'],
        fontFamily: 'Source Sans Pro',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '171 W Esplanade',
          city: 'North Vancouver',
          state: 'BC',
          country: 'Canada',
          postalCode: 'V7M 3J9',
        },
      ],
      personnel: [
        {
          name: 'Jack Newton',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/jacknewton/',
          isActive: true,
          joinedDate: '2008-01',
        },
        {
          name: 'Rian Gauvreau',
          title: 'Co-Founder & COO',
          linkedinUrl: 'https://www.linkedin.com/in/rian-gauvreau/',
          isActive: true,
          joinedDate: '2008-01',
        },
      ],
    },
    {
      name: 'Rocket Lawyer',
      domain: 'rocketlawyer.com',
      tagline: 'Legal services you can trust, at prices you can afford',
      description: 'Rocket Lawyer is an online legal services platform that provides legal documents, attorney advice, and business formation services for individuals and businesses.',
      logoUrl: 'https://logo.clearbit.com/rocketlawyer.com',
      industry: 'Legal / Legal Tech',
      keywords: ['rocket lawyer', 'legal documents', 'attorney advice', 'business formation', 'legal services'],
      seoKeywords: ['online legal documents', 'affordable attorney', 'business incorporation online', 'legal templates', 'legal advice online'],
      geoKeywords: ['rocket lawyer reviews', 'rocket lawyer vs legalzoom', 'rocket lawyer pricing'],
      competitors: [
        { name: 'LegalZoom', url: 'legalzoom.com', reason: 'Online legal services competitor' },
        { name: 'Avvo', url: 'avvo.com', reason: 'Legal marketplace competitor' },
        { name: 'LegalShield', url: 'legalshield.com', reason: 'Legal subscription service' },
        { name: 'UpCounsel', url: 'upcounsel.com', reason: 'Legal marketplace competitor' },
        { name: 'Nolo', url: 'nolo.com', reason: 'Legal information and documents' },
      ],
      valuePropositions: ['Affordable legal help', 'Document library', 'Attorney network', 'Subscription plans'],
      socialLinks: {
        twitter: 'https://twitter.com/rocketlawyer',
        linkedin: 'https://www.linkedin.com/company/rocket-lawyer',
        facebook: 'https://www.facebook.com/RocketLawyer',
        instagram: 'https://www.instagram.com/rocketlawyer',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['accessible', 'affordable', 'helpful', 'straightforward'],
        targetAudience: 'Individuals and small businesses seeking affordable legal solutions',
        keyMessages: ['Affordable legal', 'Expert help', 'Easy online', 'Trusted platform'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#E94B35',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#E94B35', '#1A1A1A', '#FFFFFF', '#F17A6A'],
        fontFamily: 'Open Sans',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '150 Spear St',
          city: 'San Francisco',
          state: 'CA',
          country: 'USA',
          postalCode: '94105',
        },
      ],
      personnel: [
        {
          name: 'Charley Moore',
          title: 'Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/charley-moore-rocket-lawyer/',
          isActive: true,
          joinedDate: '2008-01',
        },
      ],
    },
    {
      name: 'Ironclad',
      domain: 'ironcladapp.com',
      tagline: 'Digital contracting for the world\'s most innovative companies',
      description: 'Ironclad is a leading contract lifecycle management platform that helps legal teams create, negotiate, and manage contracts more efficiently.',
      logoUrl: 'https://logo.clearbit.com/ironcladapp.com',
      industry: 'Legal / Legal Tech',
      keywords: ['ironclad', 'contract management', 'CLM', 'legal operations', 'contract lifecycle'],
      seoKeywords: ['contract lifecycle management', 'contract automation', 'legal workflow software', 'contract repository', 'legal operations platform'],
      geoKeywords: ['ironclad clm', 'ironclad software', 'ironclad contracts'],
      competitors: [
        { name: 'DocuSign CLM', url: 'docusign.com/clm', reason: 'Contract management competitor' },
        { name: 'ContractWorks', url: 'contractworks.com', reason: 'Contract repository competitor' },
        { name: 'Agiloft', url: 'agiloft.com', reason: 'CLM competitor' },
        { name: 'Concord', url: 'concordnow.com', reason: 'Contract management competitor' },
        { name: 'PandaDoc', url: 'pandadoc.com', reason: 'Document automation competitor' },
      ],
      valuePropositions: ['Workflow automation', 'Self-service contracts', 'Compliance tracking', 'AI-powered insights'],
      socialLinks: {
        twitter: 'https://twitter.com/ironcladapp',
        linkedin: 'https://www.linkedin.com/company/ironcladapp',
        facebook: 'https://www.facebook.com/ironcladapp',
        instagram: 'https://www.instagram.com/ironcladapp',
      },
      voice: {
        tone: 'innovative' as const,
        personality: ['modern', 'efficient', 'legal-ops-focused', 'enterprise-ready'],
        targetAudience: 'Legal teams and businesses seeking contract automation',
        keyMessages: ['Digital contracting', 'Workflow automation', 'Legal operations', 'Contract intelligence'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#6B46FF',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#6B46FF', '#1A1A1A', '#FFFFFF', '#9B7FFF'],
        fontFamily: 'Inter',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '650 California St',
          city: 'San Francisco',
          state: 'CA',
          country: 'USA',
          postalCode: '94108',
        },
      ],
      personnel: [
        {
          name: 'Jason Boehmig',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/jboehmig/',
          isActive: true,
          joinedDate: '2014-01',
        },
        {
          name: 'Cai GoGwilt',
          title: 'Co-Founder & CTO',
          linkedinUrl: 'https://www.linkedin.com/in/caigogwilt/',
          isActive: true,
          joinedDate: '2014-01',
        },
      ],
    },
    {
      name: 'Thomson Reuters',
      domain: 'thomsonreuters.com',
      tagline: 'The answer company',
      description: 'Thomson Reuters is a global provider of business information services, delivering intelligent information to legal, tax, accounting, and compliance professionals.',
      logoUrl: 'https://logo.clearbit.com/thomsonreuters.com',
      industry: 'Legal / Legal Tech',
      keywords: ['thomson reuters', 'westlaw', 'legal research', 'legal information', 'compliance'],
      seoKeywords: ['legal research platform', 'case law research', 'legal database', 'tax research', 'compliance software'],
      geoKeywords: ['westlaw edge', 'thomson reuters westlaw', 'practical law'],
      competitors: [
        { name: 'LexisNexis', url: 'lexisnexis.com', reason: 'Legal research competitor' },
        { name: 'Bloomberg Law', url: 'bloomberglaw.com', reason: 'Legal research competitor' },
        { name: 'Fastcase', url: 'fastcase.com', reason: 'Legal research platform' },
        { name: 'vLex', url: 'vlex.com', reason: 'Legal intelligence platform' },
        { name: 'Casetext', url: 'casetext.com', reason: 'AI legal research' },
      ],
      valuePropositions: ['Comprehensive legal research', 'Trusted source', 'AI-powered insights', 'Global coverage'],
      socialLinks: {
        twitter: 'https://twitter.com/thomsonreuters',
        linkedin: 'https://www.linkedin.com/company/thomson-reuters',
        facebook: 'https://www.facebook.com/thomsonreuters',
        instagram: 'https://www.instagram.com/thomsonreuters',
        youtube: 'https://www.youtube.com/c/ThomsonReuters',
      },
      voice: {
        tone: 'authoritative' as const,
        personality: ['trusted', 'comprehensive', 'professional', 'innovative'],
        targetAudience: 'Legal, tax, and compliance professionals seeking authoritative information',
        keyMessages: ['The answer company', 'Trusted intelligence', 'Informed decisions', 'Professional-grade'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#FF8000',
        secondaryColor: '#000000',
        accentColor: '#FFFFFF',
        colorPalette: ['#FF8000', '#000000', '#FFFFFF', '#FFAD4D'],
        fontFamily: 'Knowledge',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '19 Duncan Street',
          city: 'Toronto',
          state: 'ON',
          country: 'Canada',
          postalCode: 'M5H 3H1',
        },
      ],
      personnel: [
        {
          name: 'Steve Hasker',
          title: 'President & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/steve-hasker/',
          isActive: true,
          joinedDate: '2020-03',
        },
      ],
    },
  ],
  'Mental Health / Therapy Tech': [
    {
      name: 'BetterHelp',
      domain: 'betterhelp.com',
      tagline: 'Professional therapy, on your schedule',
      description: 'BetterHelp is the world\'s largest online therapy platform, providing convenient, affordable, and accessible therapy through licensed therapists via messaging, live chat, phone, and video.',
      logoUrl: 'https://logo.clearbit.com/betterhelp.com',
      industry: 'Mental Health / Therapy Tech',
      keywords: ['betterhelp', 'online therapy', 'mental health', 'counseling', 'teletherapy'],
      seoKeywords: ['online counseling', 'virtual therapy', 'affordable therapy', 'licensed therapist', 'text therapy'],
      geoKeywords: ['betterhelp cost', 'betterhelp reviews', 'betterhelp therapists'],
      competitors: [
        { name: 'Talkspace', url: 'talkspace.com', reason: 'Online therapy competitor' },
        { name: 'Cerebral', url: 'cerebral.com', reason: 'Mental health platform' },
        { name: 'Lyra Health', url: 'lyrahealth.com', reason: 'Mental health benefits' },
        { name: 'Ginger', url: 'ginger.com', reason: 'Mental health platform' },
        { name: 'Amwell', url: 'amwell.com', reason: 'Telehealth competitor' },
      ],
      valuePropositions: ['Convenient therapy', 'Affordable access', 'Licensed therapists', 'Flexible scheduling'],
      socialLinks: {
        twitter: 'https://twitter.com/BetterHelp',
        linkedin: 'https://www.linkedin.com/company/betterhelp',
        facebook: 'https://www.facebook.com/BetterHelp',
        instagram: 'https://www.instagram.com/betterhelp',
        youtube: 'https://www.youtube.com/c/BetterHelp',
      },
      voice: {
        tone: 'empathetic' as const,
        personality: ['supportive', 'accessible', 'non-judgmental', 'caring'],
        targetAudience: 'Individuals seeking convenient, affordable therapy',
        keyMessages: ['Therapy on your schedule', 'Affordable care', 'Licensed professionals', 'You deserve support'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#00A3AD',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#00A3AD', '#1A1A1A', '#FFFFFF', '#4DC8D1'],
        fontFamily: 'Open Sans',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '990 Villa Street',
          city: 'Mountain View',
          state: 'CA',
          country: 'USA',
          postalCode: '94041',
        },
      ],
      personnel: [
        {
          name: 'Alon Matas',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/alon-matas/',
          isActive: true,
          joinedDate: '2013-01',
        },
        {
          name: 'Danny Bragonier',
          title: 'Co-Founder',
          linkedinUrl: 'https://www.linkedin.com/in/dannybragonier/',
          isActive: true,
          joinedDate: '2013-01',
        },
      ],
    },
    {
      name: 'Talkspace',
      domain: 'talkspace.com',
      tagline: 'Therapy for how we live today',
      description: 'Talkspace is a leading virtual behavioral healthcare company providing therapy, psychiatry, and medication management through an easy-to-use app.',
      logoUrl: 'https://logo.clearbit.com/talkspace.com',
      industry: 'Mental Health / Therapy Tech',
      keywords: ['talkspace', 'online therapy', 'psychiatry', 'mental health', 'telehealth'],
      seoKeywords: ['virtual therapy', 'online psychiatry', 'mental health app', 'text therapy', 'video therapy'],
      geoKeywords: ['talkspace pricing', 'talkspace psychiatry', 'talkspace insurance'],
      competitors: [
        { name: 'BetterHelp', url: 'betterhelp.com', reason: 'Online therapy competitor' },
        { name: 'Cerebral', url: 'cerebral.com', reason: 'Mental health platform' },
        { name: 'Headway', url: 'headway.co', reason: 'Therapy network' },
        { name: 'Doctor on Demand', url: 'doctorondemand.com', reason: 'Telehealth competitor' },
        { name: 'MDLive', url: 'mdlive.com', reason: 'Telehealth competitor' },
      ],
      valuePropositions: ['Therapy and psychiatry', 'Insurance accepted', 'Easy-to-use app', 'Licensed providers'],
      socialLinks: {
        twitter: 'https://twitter.com/Talkspace',
        linkedin: 'https://www.linkedin.com/company/talkspace',
        facebook: 'https://www.facebook.com/Talkspace',
        instagram: 'https://www.instagram.com/talkspace',
        youtube: 'https://www.youtube.com/c/Talkspace',
      },
      voice: {
        tone: 'supportive' as const,
        personality: ['modern', 'accessible', 'professional', 'caring'],
        targetAudience: 'Individuals seeking flexible mental health care',
        keyMessages: ['Therapy for today', 'Accessible care', 'Professional support', 'Your mental health matters'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#6B4FBB',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#6B4FBB', '#1A1A1A', '#FFFFFF', '#9B81D6'],
        fontFamily: 'Avenir Next',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '10 Jay Street',
          city: 'New York',
          state: 'NY',
          country: 'USA',
          postalCode: '10013',
        },
      ],
      personnel: [
        {
          name: 'Jon Cohen',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/jonrcohen/',
          isActive: true,
          joinedDate: '2021-09',
        },
        {
          name: 'Oren Frank',
          title: 'Co-Founder',
          linkedinUrl: 'https://www.linkedin.com/in/oren-frank/',
          isActive: true,
          joinedDate: '2012-01',
        },
      ],
    },
    {
      name: 'Calm',
      domain: 'calm.com',
      tagline: 'The #1 app for sleep, meditation, and relaxation',
      description: 'Calm is a leading mental wellness app offering guided meditations, sleep stories, breathing programs, and relaxing music to help reduce stress and anxiety.',
      logoUrl: 'https://logo.clearbit.com/calm.com',
      industry: 'Mental Health / Therapy Tech',
      keywords: ['calm', 'meditation', 'sleep', 'mindfulness', 'mental wellness'],
      seoKeywords: ['meditation app', 'sleep app', 'mindfulness app', 'stress relief', 'anxiety relief app'],
      geoKeywords: ['calm app', 'calm premium', 'calm subscription'],
      competitors: [
        { name: 'Headspace', url: 'headspace.com', reason: 'Meditation app competitor' },
        { name: 'Insight Timer', url: 'insighttimer.com', reason: 'Meditation app competitor' },
        { name: 'Ten Percent Happier', url: 'tenpercent.com', reason: 'Meditation app competitor' },
        { name: 'Simple Habit', url: 'simplehabit.com', reason: 'Meditation app competitor' },
        { name: 'Breethe', url: 'breethe.com', reason: 'Meditation and sleep app' },
      ],
      valuePropositions: ['Sleep stories', 'Guided meditations', 'Breathing exercises', 'Mental wellness'],
      socialLinks: {
        twitter: 'https://twitter.com/calm',
        linkedin: 'https://www.linkedin.com/company/calm-com',
        facebook: 'https://www.facebook.com/calm',
        instagram: 'https://www.instagram.com/calm',
        youtube: 'https://www.youtube.com/c/calm',
      },
      voice: {
        tone: 'calming' as const,
        personality: ['peaceful', 'soothing', 'mindful', 'supportive'],
        targetAudience: 'Individuals seeking stress relief, better sleep, and mindfulness',
        keyMessages: ['Less stress, more sleep', 'Find your calm', 'Mental wellness', 'Peace of mind'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#2196F3',
        secondaryColor: '#0D47A1',
        accentColor: '#FFFFFF',
        colorPalette: ['#2196F3', '#0D47A1', '#FFFFFF', '#64B5F6'],
        fontFamily: 'Moderat',
      },
      benchmarkTier: 'gold' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '114 Sansome Street',
          city: 'San Francisco',
          state: 'CA',
          country: 'USA',
          postalCode: '94104',
        },
      ],
      personnel: [
        {
          name: 'David Ko',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/davidjko/',
          isActive: true,
          joinedDate: '2020-07',
        },
        {
          name: 'Michael Acton Smith',
          title: 'Co-Founder',
          linkedinUrl: 'https://www.linkedin.com/in/michaelactonsmith/',
          isActive: true,
          joinedDate: '2012-01',
        },
      ],
    },
    {
      name: 'Headspace',
      domain: 'headspace.com',
      tagline: 'Meditation and sleep made simple',
      description: 'Headspace is a digital health platform providing guided meditation, mindfulness, sleep, and mental health support through an app and content.',
      logoUrl: 'https://logo.clearbit.com/headspace.com',
      industry: 'Mental Health / Therapy Tech',
      keywords: ['headspace', 'meditation', 'mindfulness', 'mental health', 'sleep'],
      seoKeywords: ['guided meditation app', 'mindfulness meditation', 'sleep meditation', 'stress management app', 'mental health app'],
      geoKeywords: ['headspace app', 'headspace plus', 'headspace for work'],
      competitors: [
        { name: 'Calm', url: 'calm.com', reason: 'Meditation app competitor' },
        { name: 'Insight Timer', url: 'insighttimer.com', reason: 'Meditation app competitor' },
        { name: 'Simple Habit', url: 'simplehabit.com', reason: 'Meditation app competitor' },
        { name: 'Aura', url: 'aurahealth.io', reason: 'Mental wellness app' },
        { name: 'Sanvello', url: 'sanvello.com', reason: 'Mental health app' },
      ],
      valuePropositions: ['Science-backed', 'Easy to use', 'Expert guidance', 'Mental health support'],
      socialLinks: {
        twitter: 'https://twitter.com/headspace',
        linkedin: 'https://www.linkedin.com/company/headspace-meditation-limited',
        facebook: 'https://www.facebook.com/headspace',
        instagram: 'https://www.instagram.com/headspace',
        youtube: 'https://www.youtube.com/c/headspace',
      },
      voice: {
        tone: 'friendly' as const,
        personality: ['approachable', 'mindful', 'supportive', 'science-based'],
        targetAudience: 'Individuals seeking meditation and mental wellness tools',
        keyMessages: ['Meditation made simple', 'Science-backed', 'Mental health matters', 'Be kind to your mind'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#F77737',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#F77737', '#1A1A1A', '#FFFFFF', '#FA9F6F'],
        fontFamily: 'Headspace Sans',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '2415 Michigan Ave',
          city: 'Santa Monica',
          state: 'CA',
          country: 'USA',
          postalCode: '90404',
        },
      ],
      personnel: [
        {
          name: 'Russell Glass',
          title: 'CEO',
          linkedinUrl: 'https://www.linkedin.com/in/russellglass/',
          isActive: true,
          joinedDate: '2021-11',
        },
        {
          name: 'Andy Puddicombe',
          title: 'Co-Founder',
          linkedinUrl: 'https://www.linkedin.com/in/andy-puddicombe/',
          isActive: true,
          joinedDate: '2010-01',
        },
      ],
    },
    {
      name: 'Lyra Health',
      domain: 'lyrahealth.com',
      tagline: 'Workforce mental health that works',
      description: 'Lyra Health provides comprehensive mental health benefits for employees, offering therapy, coaching, medication management, and self-care tools.',
      logoUrl: 'https://logo.clearbit.com/lyrahealth.com',
      industry: 'Mental Health / Therapy Tech',
      keywords: ['lyra health', 'employee mental health', 'workplace wellness', 'mental health benefits', 'EAP'],
      seoKeywords: ['employee mental health benefits', 'workplace mental wellness', 'corporate mental health', 'employee assistance program', 'mental health platform'],
      geoKeywords: ['lyra health benefits', 'lyra health employers', 'lyra health providers'],
      competitors: [
        { name: 'Spring Health', url: 'springhealth.com', reason: 'Workplace mental health' },
        { name: 'Ginger', url: 'ginger.com', reason: 'Employee mental health platform' },
        { name: 'Modern Health', url: 'modernhealth.com', reason: 'Mental wellness benefits' },
        { name: 'Cigna EAP', url: 'cigna.com/eap', reason: 'Traditional EAP competitor' },
        { name: 'ComPsych', url: 'compsych.com', reason: 'EAP competitor' },
      ],
      valuePropositions: ['Comprehensive care', 'Provider matching', 'Evidence-based', 'Employer benefits'],
      socialLinks: {
        twitter: 'https://twitter.com/lyrahealth',
        linkedin: 'https://www.linkedin.com/company/lyra-health',
        facebook: 'https://www.facebook.com/lyrahealth',
        instagram: 'https://www.instagram.com/lyrahealth',
      },
      voice: {
        tone: 'professional' as const,
        personality: ['evidence-based', 'supportive', 'employer-focused', 'comprehensive'],
        targetAudience: 'Employers and HR teams seeking mental health benefits',
        keyMessages: ['Workforce mental health', 'Evidence-based care', 'Better outcomes', 'Comprehensive support'],
        avoidTopics: [],
      },
      visual: {
        primaryColor: '#00C9A7',
        secondaryColor: '#1A1A1A',
        accentColor: '#FFFFFF',
        colorPalette: ['#00C9A7', '#1A1A1A', '#FFFFFF', '#4DDDC4'],
        fontFamily: 'Inter',
      },
      benchmarkTier: 'silver' as const,
      locations: [
        {
          type: 'headquarters' as const,
          address: '269 East Grand Ave',
          city: 'Burlingame',
          state: 'CA',
          country: 'USA',
          postalCode: '94010',
        },
      ],
      personnel: [
        {
          name: 'David Ebersman',
          title: 'Co-Founder & CEO',
          linkedinUrl: 'https://www.linkedin.com/in/david-ebersman/',
          isActive: true,
          joinedDate: '2015-01',
        },
        {
          name: 'Dena Bravata',
          title: 'Co-Founder & Chief Medical Officer',
          linkedinUrl: 'https://www.linkedin.com/in/dena-bravata-md-ms-3647a31/',
          isActive: true,
          joinedDate: '2015-01',
        },
      ],
    },
  ],
};

async function main() {
  console.log('Adding 5 new industries (25 brands) to expand to 125 total benchmark brands...\n');

  // Check if org exists
  const org = await db.query.organizations.findFirst({
    where: eq(organizations.id, 'org_benchmark_brands'),
  });

  if (!org) {
    console.error('ERROR: Organization "org_benchmark_brands" not found!');
    process.exit(1);
  }

  console.log('Organization found:', org.name);
  console.log('');

  let totalInserted = 0;
  let totalSkipped = 0;
  let totalErrors = 0;

  for (const [industry, brandsData] of Object.entries(NEW_INDUSTRIES)) {
    console.log(`Processing industry: ${industry}`);
    console.log('='.repeat(60));

    for (const brandData of brandsData) {
      try {
        // Check if brand already exists by domain
        const existing = await db.query.brands.findFirst({
          where: eq(brands.domain, brandData.domain),
        });

        if (existing) {
          console.log(`⏭️  SKIPPED: ${brandData.name} (${brandData.domain}) - already exists`);
          totalSkipped++;
          continue;
        }

        // Insert brand
        await db.insert(brands).values({
          organizationId: 'org_benchmark_brands',
          isBenchmark: true,
          ...brandData,
        });

        console.log(`✅ INSERTED: ${brandData.name} (${brandData.domain}) - ${brandData.benchmarkTier} tier`);
        totalInserted++;

        // Small delay to avoid overwhelming the database
        await new Promise((resolve) => setTimeout(resolve, 300));
      } catch (error) {
        console.error(`❌ ERROR inserting ${brandData.name}:`, error);
        totalErrors++;
      }
    }

    console.log('');
  }

  console.log('='.repeat(60));
  console.log('SUMMARY:');
  console.log(`✅ Inserted: ${totalInserted}`);
  console.log(`⏭️  Skipped: ${totalSkipped}`);
  console.log(`❌ Errors: ${totalErrors}`);
  console.log('='.repeat(60));

  if (totalInserted === 25) {
    console.log('\n🎉🎉🎉 125 BENCHMARK BRANDS COMPLETE! 🎉🎉🎉');
    console.log('All 25 industries now have 5 brands each (3 gold + 2 silver)');
    console.log('\nRun count-brands.ts to verify!');
  } else {
    console.log(`\n⚠️  Expected to insert 25 brands but inserted ${totalInserted}`);
    console.log('Some brands may already exist in the database.');
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
