#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 017: AI Content Generation

set -e

echo "========================================"
echo "AI Content Generation - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment variables..."

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${YELLOW}Warning: ANTHROPIC_API_KEY not set${NC}"
    echo "Add to .env.local: ANTHROPIC_API_KEY=your_key_here"
fi

if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${YELLOW}Warning: OPENAI_API_KEY not set${NC}"
    echo "Add to .env.local: OPENAI_API_KEY=your_key_here"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js dev server
npm run dev &

# Wait for Next.js
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Next Steps:"
echo "  1. Verify API keys are configured (ANTHROPIC_API_KEY, OPENAI_API_KEY)"
echo "  2. Run tests: npm run test"
echo "  3. Navigate to content generation form"
echo ""
echo "Implementation Plan:"
echo "  - Phase 1: Foundation (types & validation)"
echo "  - Phase 2: GEO Prompt Templates"
echo "  - Phase 3: AI Content Generator"
echo "  - Phase 4: API Route"
echo "  - Phase 5: Frontend Component"
echo "  - Phase 6: Integration Testing"
echo ""
